version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 1234:1234
    depends_on:
      - service

  service:
    build:
      context: ./service
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./service:/app
    ports:
      - 8080:8080
    depends_on:
      - mongo
  
  mongo:
    image: mongo:4.0.9
    volumes:
      - ./service/data:/data/db
    ports:
      - 27018:27017